//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWYResFactory {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BWYResFactory.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 没有表结构 的本地化字符串。
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源:{0} 不存在 的本地化字符串。
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the RowIndex:{0} has been Deleted 的本地化字符串。
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经存在 的本地化字符串。
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找ModelTreeTemp文件的节点时出错：找不到节点 的本地化字符串。
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性{0}不存在 的本地化字符串。
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确保比较的双方类型一致 的本地化字符串。
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该行状态处于已被删除 的本地化字符串。
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户{0}不存在 的本地化字符串。
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表{0},字段{1},值有效性验证不通过，表达式{2} 的本地化字符串。
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统无法识别的表对象，请使用模型实例化表对象。 的本地化字符串。
        /// </summary>
        internal static string _520 {
            get {
                return ResourceManager.GetString("520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTable 不能为Null 的本地化字符串。
        /// </summary>
        internal static string _521 {
            get {
                return ResourceManager.GetString("521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少需要有一个数据层服务是当前连接。 的本地化字符串。
        /// </summary>
        internal static string _522 {
            get {
                return ResourceManager.GetString("522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DALServer 的本地化字符串。
        /// </summary>
        internal static string DALServerName {
            get {
                return ResourceManager.GetString("DALServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BWYDB_Log 的本地化字符串。
        /// </summary>
        internal static string LogDBNm {
            get {
                return ResourceManager.GetString("LogDBNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider=OraOLEDB.Oracle.1;User ID={0};Password={1};Data Source=(DESCRIPTION = (ADDRESS_LIST= (ADDRESS = (PROTOCOL = TCP)(HOST = {2})(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = {3}))) 的本地化字符串。
        /// </summary>
        internal static string ORACLECONN {
            get {
                return ResourceManager.GetString("ORACLECONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTye{0}{1}{2}ConnectStr{0}{3}{2}ConnectType{0}{4} 的本地化字符串。
        /// </summary>
        internal static string SaveStr {
            get {
                return ResourceManager.GetString("SaveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string SQLAnd {
            get {
                return ResourceManager.GetString("SQLAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  From  的本地化字符串。
        /// </summary>
        internal static string SQLFrom {
            get {
                return ResourceManager.GetString("SQLFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group By 的本地化字符串。
        /// </summary>
        internal static string SQLGroup {
            get {
                return ResourceManager.GetString("SQLGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Join 的本地化字符串。
        /// </summary>
        internal static string SQLLeftJoin {
            get {
                return ResourceManager.GetString("SQLLeftJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string SQLOn {
            get {
                return ResourceManager.GetString("SQLOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string SQLOr {
            get {
                return ResourceManager.GetString("SQLOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 的本地化字符串。
        /// </summary>
        internal static string SQLSelect {
            get {
                return ResourceManager.GetString("SQLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 server={0};database={1};uid={2};password={3} 的本地化字符串。
        /// </summary>
        internal static string SQLSERVERCONN {
            get {
                return ResourceManager.GetString("SQLSERVERCONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string SQLUpdate {
            get {
                return ResourceManager.GetString("SQLUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where 的本地化字符串。
        /// </summary>
        internal static string SQLWhere {
            get {
                return ResourceManager.GetString("SQLWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BWYDB_SYS 的本地化字符串。
        /// </summary>
        internal static string SysDBNm {
            get {
                return ResourceManager.GetString("SysDBNm", resourceCulture);
            }
        }
    }
}
